---
fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.18.0"
    apt:
      ref: "4.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    docker:
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
      ref: " 1.0.4"
    vision_docker:
      repo: "https://github.com/vision-it/vision-docker"
      ref: "origin/production"
  symlinks:
    vision_puppetdb: '#{source_dir}'
