---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "5.0.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    docker:
      ref: "3.5.0"
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
    vision_docker:
      repo: "https://github.com/vision-it/vision-docker"
      ref: "origin/production"
  symlinks:
    vision_puppetdb: '#{source_dir}'
