---
fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.18.0"
    apt:
      ref: "2.3.0"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    docker:
      repo: "https://github.com/garethr/garethr-docker"
      ref: " v5.3.0"
    vision_docker:
      repo: "https://github.com/vision-it/vision-docker"
      ref: "origin/production"
  symlinks:
    vision_puppetdb: '#{source_dir}'
